"""SOV (Sources of Variation Analyzer) contracts.

This package contains Pydantic models for SOV-specific data structures:
- ANOVA contracts for analysis of variance results
- Variance components contracts for hierarchical variance decomposition
- Visualization contracts for chart/plot specifications
- Pipeline contracts for analysis pipeline stages (ADR-0023)
- DataSet I/O contracts for data loading and output (ADR-0024)

All contracts are domain-agnostic; user-specific knowledge (factor names,
response columns, grouping levels) is injected via analysis configs.
"""

from shared.contracts.sov.anova import (
    AnalysisRequest,
    AnalysisResult,
    ANOVAConfig,
    ANOVAResult,
    ANOVAResultRef,
    ANOVASummary,
    FactorEffect,
    PostHocResult,
    PostHocTest,
    VarianceComponent,
    VarianceComponentsConfig,
    VarianceComponentsResult,
)
from shared.contracts.sov.dataset_io import (
    ANOVATableOutput,
    ANOVATableRow,
    DataSetLoadRequest,
    DataSetLoadResult,
    DataSetOutputConfig,
    DataSetOutputResult,
    DataSetValidationResult,
    GroupMeansOutput,
    GroupMeansRow,
    OutputColumn,
    PostHocTableOutput,
    PostHocTableRow,
    SignificanceLevel,
    SOVColumnMeta,
    SOVColumnRole,
    SOVFactorType,
    SOVResultsBundle,
    VarianceComponentRow,
    VarianceComponentsOutput,
)
from shared.contracts.sov.pipeline import (
    ANOVAComputationConfig,
    ANOVAComputationResult,
    CancelPipelineRequest,
    CreatePipelineRequest,
    DataIngestionConfig,
    DataIngestionResult,
    FactorIdentificationConfig,
    FactorIdentificationResult,
    PipelineProgressUpdate,
    SOVPipeline,
    SOVPipelineConfig,
    SOVPipelineRef,
    SOVPipelineState,
    SOVStageId,
    SOVStageState,
    SOVStageStatus,
    StartPipelineRequest,
    VarianceDecompositionConfig,
    VarianceDecompositionResult,
    VisualizationPreparationConfig,
    VisualizationPreparationResult,
)
from shared.contracts.sov.visualization import (
    BoxPlotConfig,
    ColorPalette,
    InteractionPlotConfig,
    MainEffectsPlotConfig,
    NormalProbabilityPlotConfig,
    PlotStyle,
    ResidualPlotConfig,
    VarianceBarConfig,
    VisualizationResult,
    VisualizationSpec,
    VisualizationType,
)

__all__ = [
    # ANOVA contracts
    "ANOVAConfig",
    "ANOVAResult",
    "ANOVAResultRef",
    "ANOVASummary",
    "FactorEffect",
    "VarianceComponent",
    "VarianceComponentsConfig",
    "VarianceComponentsResult",
    "PostHocTest",
    "PostHocResult",
    "AnalysisRequest",
    "AnalysisResult",
    # Visualization contracts
    "VisualizationType",
    "VisualizationSpec",
    "VisualizationResult",
    "BoxPlotConfig",
    "InteractionPlotConfig",
    "MainEffectsPlotConfig",
    "VarianceBarConfig",
    "ResidualPlotConfig",
    "NormalProbabilityPlotConfig",
    "PlotStyle",
    "ColorPalette",
    # Pipeline contracts (ADR-0023)
    "SOVStageId",
    "SOVStageState",
    "SOVPipelineState",
    "DataIngestionConfig",
    "FactorIdentificationConfig",
    "ANOVAComputationConfig",
    "VarianceDecompositionConfig",
    "VisualizationPreparationConfig",
    "DataIngestionResult",
    "FactorIdentificationResult",
    "ANOVAComputationResult",
    "VarianceDecompositionResult",
    "VisualizationPreparationResult",
    "SOVStageStatus",
    "SOVPipelineConfig",
    "SOVPipeline",
    "SOVPipelineRef",
    "CreatePipelineRequest",
    "StartPipelineRequest",
    "CancelPipelineRequest",
    "PipelineProgressUpdate",
    # DataSet I/O contracts (ADR-0024)
    "SOVColumnRole",
    "SOVFactorType",
    "SignificanceLevel",
    "SOVColumnMeta",
    "DataSetLoadRequest",
    "DataSetLoadResult",
    "DataSetValidationResult",
    "OutputColumn",
    "DataSetOutputConfig",
    "DataSetOutputResult",
    "ANOVATableRow",
    "ANOVATableOutput",
    "PostHocTableRow",
    "PostHocTableOutput",
    "GroupMeansRow",
    "GroupMeansOutput",
    "VarianceComponentRow",
    "VarianceComponentsOutput",
    "SOVResultsBundle",
]
