"""DevTools contracts package.

Per ADR-0028: DevTools Page Architecture.

Exports all DevTools-related Pydantic contracts.
"""

from shared.contracts.devtools.api import (
    ADRContent,
    ADRDeleteRequest,
    ADRDeleteResponse,
    ADRListItem,
    ADRListResponse,
    ADRReadResponse,
    ADRSaveRequest,
    ADRSaveResponse,
    ADRScope,
    ADRStatus,
    ADRValidationRequest,
    ADRValidationResponse,
    APITestRequest,
    APITestResponse,
    ConfigFileInfo,
    ConfigFileListResponse,
    ConfigFileReadResponse,
    ConfigFileSaveRequest,
    ConfigFileSaveResponse,
    ConfigFileType,
    DevToolsInfo,
    DevToolsState,
    DevToolsToggleRequest,
    DevToolsToggleResponse,
    SchemaValidationRequest,
    SchemaValidationResponse,
)
from shared.contracts.devtools.discussion import (
    Constraint,
    ConversationLogEntry,
    DecisionPoint,
    DecisionStatus,
    DiscussionContext,
    DiscussionCreateRequest,
    DiscussionCreateResponse,
    DiscussionRequirements,
    DiscussionResolution,
    DiscussionSchema,
    DiscussionStatus,
    DiscussionSummaryForPrompt,
    DiscussionUpdateRequest,
    FunctionalRequirement,
    NonFunctionalRequirement,
    OpenQuestion,
    OptionConsidered,
    QuestionStatus,
    ResultingArtifact,
    ScopeDefinition,
)
from shared.contracts.devtools.fragment import (
    Fragment,
    FragmentExecution,
    FragmentListResponse,
    FragmentStatus,
    MilestoneFragment,
    VerificationResult,
)
from shared.contracts.devtools.workflow import (
    ArtifactListResponse,
    ArtifactResponse,
    ArtifactStatus,
    ArtifactSummary,
    ArtifactType,
    CreateArtifactRequest,
    GraphEdge,
    GraphNode,
    GraphResponse,
    RelationshipType,
    UpdateArtifactRequest,
)

__version__ = "0.1.0"

__all__ = [
    # Workflow Manager (ADR-0045)
    "ArtifactType",
    "ArtifactStatus",
    "ArtifactSummary",
    "ArtifactListResponse",
    "ArtifactResponse",
    "CreateArtifactRequest",
    "UpdateArtifactRequest",
    "GraphNode",
    "GraphEdge",
    "GraphResponse",
    "RelationshipType",
    # Discussion (T0 tier - ADR-0043, DISC-002)
    "DiscussionSchema",
    "DiscussionStatus",
    "DiscussionRequirements",
    "DiscussionContext",
    "DiscussionResolution",
    "DiscussionCreateRequest",
    "DiscussionCreateResponse",
    "DiscussionUpdateRequest",
    "DiscussionSummaryForPrompt",
    "FunctionalRequirement",
    "NonFunctionalRequirement",
    "OpenQuestion",
    "QuestionStatus",
    "OptionConsidered",
    "DecisionPoint",
    "DecisionStatus",
    "Constraint",
    "ResultingArtifact",
    "ConversationLogEntry",
    "ScopeDefinition",
    # Fragment (T5 tier - ADR-0043)
    "Fragment",
    "FragmentStatus",
    "FragmentExecution",
    "FragmentListResponse",
    "MilestoneFragment",
    "VerificationResult",
    # DevTools State
    "DevToolsState",
    "DevToolsToggleRequest",
    "DevToolsToggleResponse",
    "DevToolsInfo",
    # ADR Management
    "ADRScope",
    "ADRStatus",
    "ADRListItem",
    "ADRListResponse",
    "ADRContent",
    "ADRReadResponse",
    "ADRSaveRequest",
    "ADRSaveResponse",
    "ADRDeleteRequest",
    "ADRDeleteResponse",
    "ADRValidationRequest",
    "ADRValidationResponse",
    # Config Management
    "ConfigFileType",
    "ConfigFileInfo",
    "ConfigFileListResponse",
    "ConfigFileReadResponse",
    "ConfigFileSaveRequest",
    "ConfigFileSaveResponse",
    # Utilities
    "SchemaValidationRequest",
    "SchemaValidationResponse",
    "APITestRequest",
    "APITestResponse",
]
